## File generated by the BNF Converter (bnfc 2.9.6.1).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Basic/Test

# Rules for building the parser.

Basic/Abs.hs Basic/Lex.x Basic/Par.y Basic/Print.hs Basic/Test.hs : basic.cf
	bnfc --haskell -d basic.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Basic/Test : Basic/Abs.hs Basic/Lex.hs Basic/Par.hs Basic/Print.hs Basic/Test.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f Basic/*.hi Basic/*.o Basic/*.log Basic/*.aux Basic/*.dvi

distclean : clean
	-rm -f Basic/Abs.hs Basic/Abs.hs.bak Basic/ComposOp.hs Basic/ComposOp.hs.bak Basic/Doc.txt Basic/Doc.txt.bak Basic/ErrM.hs Basic/ErrM.hs.bak Basic/Layout.hs Basic/Layout.hs.bak Basic/Lex.x Basic/Lex.x.bak Basic/Par.y Basic/Par.y.bak Basic/Print.hs Basic/Print.hs.bak Basic/Skel.hs Basic/Skel.hs.bak Basic/Test.hs Basic/Test.hs.bak Basic/XML.hs Basic/XML.hs.bak Basic/AST.agda Basic/AST.agda.bak Basic/Parser.agda Basic/Parser.agda.bak Basic/IOLib.agda Basic/IOLib.agda.bak Basic/Main.agda Basic/Main.agda.bak Basic/basic.dtd Basic/basic.dtd.bak Basic/Test Basic/Lex.hs Basic/Par.hs Basic/Par.info Basic/ParData.hs Makefile
	-rmdir -p Basic/

# EOF
